### ISSUE TITLE
validateClass() not working as expected

### ISSUE THREAD

**Issue by SunnySoldier357** [Azure-Samples/active-directory-android#12]
I have a class called Assignment which extended an abstract class TableData. Because my id, version ,etc was defined in TableData, I did not define it again in Assignment but the validateClass() in the MobileServiceClient class kept giving the error "The class representing the MobileServiceTable must have a single id property defined". The problem was that it only checked for fields in the class itself not the TableData class.
I tried changing the TableData class to non-abstract class but it still did not work

**Comment by danieldobalian** [comment]
Hi @SunnySoldier357, I'm having a hard time parsing your issue/question. Was this the repo you ran into problems w/, the referenced methods and classes look fairly different than what's here.

**Comment by danieldobalian** [comment]
Closing as we've changed this sample quite a bit and I suspect it no longer applies.
