### ISSUE TITLE
how can i login with microsoft Account?

### ISSUE THREAD

**Issue by PINALDHADUK** [Azure-Samples/active-directory-android#21]
i used this demo but its giving this error.
whats problem is there i don`t understand please help me.
AADSTS50020: We are unable to issue tokens from this api version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/azure-samples/ms-identity-android-native
