### ISSUE TITLE
How to know if MFA is enabled or not?

### ISSUE THREAD

**Issue by dharashahkenya** [Azure-Samples/active-directory-android#22]
Hi,

I have implemented Microsoft sign-in just the way it is in this sample app. However, i am not able to get the urls back from the webview, or even not able to identify if the user email address is mfa enabled or not. Is there a way this can be detected?

pls assist

Thans

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/azure-samples/ms-identity-android-native
