### ISSUE TITLE
how to set broker true?

### ISSUE THREAD

**Issue by bhandaribhumin** [Azure-Samples/active-directory-android#24]
i want to open microsoft authenticator app while click call graph api so how do i set broker true in sample code?

**Comment by harry2845** [comment]
Add this in onCreate:
AuthenticationSettings.INSTANCE.setUseBroker(true);

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/azure-samples/ms-identity-android-native
