### ISSUE TITLE
It looks like Sample Web API Single Sign-On for .Net and this client is out of sync

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure-Samples/active-directory-android#7]
I tried AzureADSamples/NativeClient-DotNet and it works fine, but AzureADSamples/NativeClient-Android doesn't work with Microsoft Azure Active Directory Sample Web API Single Sign-On for .Net.

**Comment by brandwe** [comment]
We are going to unify the Web APIs between node.js and .Net soon.
